spring:
  profiles:
    active: local
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    serialization:
      write_dates_as_timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    root: info
    org:
      springframework:
        web: info

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
    disable-ssl-validation: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

